# Generated by Django 6.0.5 on 2026-06-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulabase',
            name='medico',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
