# Generated by Django 6.0.5 on 2026-06-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion', '0005_detalleregistrocontrato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleRegistroContrato',
        ),
    ]
